#Base.include(@__MODULE__,"input_interface.jl")
#Base.include(@__MODULE__,"../molecule/molecule_interface.jl")
#Base.include(@__MODULE__,"../rhf/rhf_interface.jl")
#Base.include(@__MODULE__,"../properties/properties_interface.jl")

push!(LOAD_PATH,"./")
push!(LOAD_PATH,"src/eri")
push!(LOAD_PATH,"src/input")
push!(LOAD_PATH,"src/math")
push!(LOAD_PATH,"src/molecule")
push!(LOAD_PATH,"src/properties")
push!(LOAD_PATH,"src/rhf")
